package com.samsung.util;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nogah' at '17. 1. 10 오후 5:26' with Gradle 3.2.1
 *
 * @author nogah, @date 17. 1. 10 오후 5:26
 */
public class Library {
    public static boolean someLibraryMethod() {
        return true;
    }

	public static int sumValue(int a,int b) {
        return a+b;
    }
}
